#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 11 21:03:07 2016


QUESTION
--------

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Find the letter that was added in t.

@author: pratik18v
"""

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        return chr(reduce(operator.xor,map(ord, s) + map(ord,t)))
        
if __name__ == '__main__':
    s = "abcd"
    t = "abcde"
    sol = Solution()
    ans = sol.findTheDifference(s,t)
    print 'The extra character is: {}'.format(ans)